//define all entries here
academic_entries = [
new Entry([],"2015 - Present", 201509, 2019, "bu", "Brown University", "Bachelor of Arts in Computer Science and Comparative Literature", "Providence, RI", [], "http://www.brown.edu/academics"),
new Entry([],"2011 - 2015", 201109, 201506, "bhsecq", "Bard High School Early College Queens", "Bard College Associate of Arts in Liberal Arts; High School Diploma", "Long Island City, NY", [], "http://bhsec.bard.edu/queens/"),
new Entry([],"2008 - 2011", 200809, 201106, "ice","Institute for Collaborative Education", "Middle School"),
new Entry([],"2002 - 2008", 200209, 200806, "ps261", "PS 261", "Elementary School"),
];
extra_entries = [
new Entry(["learn", "cs", "women"],"Jul - Aug 2013", 20130708, 20130830, "gwc", "Girls Who Code", "Student", "New York, NY", 
	["Selected to participate in a full-time intensive (8 hours a day for 8 weeks) computer programming workshop for teen girls", 
	"Learned new skills and languages through various projects, 20 field trips, and 30+ speakers", 
	"Created projects from the idea to the product, and presented work with pitches and demos",
	"Built a sisterhood with other girls as part of a national movement"], "http://girlswhocode.com/"),
new Entry(["club", "cs", "teach"],"Feb 2014 - Jun 2015", 201402, 201506, "bhsecgwc", "Bard High School Early College Queens Girls Who Code Club", "Co-founder, Co-leader/Curriculum Director (Sept 2014 - Jun 2015)", "Long Island City, NY",
	["Helped members with curriculum using knowledge gained in the GWC summer program", 
	"Worked with two outside computer programmers to teach all interested students to code in a supportive, collaborative environment"]),
new Entry(["prof","cs", "teach"],"Sept 2013 - Jun 2014", 201309, 201406, "pixelaca", "Pixel Academy", "Intern", "Brooklyn, NY", 
	["Helped instructors teach kids different ways to be creative with technology (coding, games, 3D-design, etc) both one-on-one and through group workshops",
	"Worked on personal project under the instructors’ guidance"], "http://www.pixelacademy.org/"),
new Entry(["hum"],"Sept 2012 - Jun 2015", 201209, 201506, "gwn", "Girls Write Now", "Mentee", "New York, NY", 
	["Met with mentor once a week and established a constructive relationship",
	"Wrote fiction and memoir pieces individually between meetings",
	"Explored new fields of writing at group workshops held once a month",
	"Used feedback and criticism from others to improve"], "http://www.girlswritenow.org/"),
new Entry(["learn"], "Apr 2005 - Jun 2015", 200504, 201506, "tachibana", "Tachibana Japanese Dance Group", "Dancer", "New York Branch, NY", 
	["Learned the art of traditional Japanese dance while coordinating with other dancers",
	"Performed 4-5 times a year at the annual recital, New Year’s dance ritual, and other events at elderly homes and cultural venues in New York"]),
new Entry(["club", "hum"], "Oct 2012 - Jun 2015", 201210, 201506, "bhsecgov", "Bard High School Early College Queens Student Government", "Minute-taker (all), Elected Advisory Representative (Sept 2013 - Jun 2015)", "Long Island City, NY",
	["Listened and responded to others’ opinions", "Recorded ideas and oppositions in a clear, concise way",
	"Created the minute-taker role for organization and school community awareness"]),
new Entry(["club", "teach"], "Oct 2012 - Jun 2015", 201210, 201506, "bhsecpeertutor", "Bard High School Early College Queens Peer Tutoring", "Biology (Fall 2012), Writing/English (all), Math (all) peer tutor", "Long Island City, NY",
	["Helped fellow students with homework, test preparation and more"]),
new Entry(["hum"], "Feb 2012 - Dec 2013, Sept 2014 - Feb 2015", 201202, 201502, "bhseclibrary", "Bard High School Early College Queens Library", "Intern","Long Island City, NY",
	["Helped students at the desk by checking books in and out, helping with homework, and directing students to the right section of the library",
	"Recommended, ordered, and catalogued new books",
	"Familiarized myself with library software"]),
new Entry(["club","math"], "Oct 2014 - Jul 2015", 201410, 201507, "bhsecteams", "Bard High School Early College Queens TEAMS (Test of Engineering Aptitude, Mathematics, and Science) Club", "Team Member", "Long Island City, NY",
	["Recruited to this eight-member team by a classmate", 
	"Discussed and solved real-world problem sets", 
	"Participated in the state and national TEAMS Competitions in Texas"]),
new Entry(["natsci", "club"], "Nov 2014 - Jan 2015", 201411, 201501, "brainbee", "NY Region Brain Bee Competition", "School Representative (1 of 2)","Long Island City, NY",
	["Discussed neuroscience knowledge with other representative and professor during weekly meetings", 
	"Independently studied neuroscience information material and books to prepare for January 31 competition"],"http://www.dana.org/nycbrainbee/"),
new Entry(["club"], "Sept 2011 - Jun 2013", 201109, 201306, "bhsecqa", "Bard High School Early College Queens Queer-Straight Alliance", "Member (2011-2012), Co-leader (2012-13)","Long Island City, NY",
	["Cooperated and exchanged ideas with other leaders",
	"Planned events and meetings including workshops, discussions, and school community outreach"]),
new Entry(["prof","lang"], "Sept 2014 - Feb 2015", 201409, 201502, "jtranslation", "Private Translation", "", 
	["Worked for an independent filmmaker to translate raw footage in Japanese to English"]),
new Entry(["prof","hum","lang"], "Summers of 2010, 2011, 2012, 2013, and 2015", 201006, 201508, "upaf","Uno Port Art Films", "Assistant to Directors (2011 - Present)", "Okayama, Japan",
	["Participated in this annual mainly-outdoor non-profit film festival in Japan that shows cutting-edge films from around the world", 
	"Translated (English-Japanese, Japanese-English) and subtitled (using Final Cut Pro) a total of 5 films individually, while co-translating and co-subtitling 24 films",
	"Took charge of ticketing in the box office, sales of merchandise (T-shirts, bags), and records"], "http://unoportartfilms.org/en/"),
new Entry(["vol", "lang"], "Jul - Aug 2014", 20140721, 20140809, "obras", "Obras Sociales de Santo Hermano Pedro","Volunteer with Proyecto Nutricional", "Antigua Guatemala, Guatemala",
	["Cared for hospitalized babies and children (suffering from malnoutrition, Down Syndrome, and/or awaiting cleft palate surgery) by bottle feeding, carrying, and making them laugh",
	"Spoke to staff, parents and children exclusively in Spanish to communicate"]),
new Entry(["learn","lang"], "Jun - Aug 2014", 20140630, 20140808, "antiguena", "Spanish Academy Antigueña", "Student","Antigua Guatemala, Guatemala", 
	["Created a curriculum to study Spanish grammar and Guatemalan culture daily with native Guatemalan teachers",
	"Arranged a homestay with a Guatemalan family in Antigua Guatemala through this school"]),
new Entry(["prof", "teach"], "Dec 2010 - Jun 2013", 201012, 201306, "ktutoring", "Private Tutoring", "", "Brooklyn, NY",
	["Taught English, reading comprehension, and math for homework and in preparation for NY standardized tests",
	"Worked with neighborhood children, most of whom needed tutoring to advance to the next grade level"]),
new Entry(["vol","teach"], "Dec 2012 - Jun 2013", 201212, 201306, "starlearning", "Goddard Community Center, Star Learning Center", "Volunteer Tutor", "New York, NY",
	["Taught English and math to a 2nd grader at a NYC community center"], "http://www.goddard.org/page/tutoring-at-star-learning-center-58.html"),
new Entry(["cs","prof"],"Sept 2015 - Present", 201509, today(), "brownweb", "Brown WebServices", "Web Developer Intern", "Providence, RI", 
	["Use HTML/CSS/PHP and learn Drupal 6 and 7 to create and modify Brown University sites",
	"Work with a team of interns and staff to collaboratively solve problems, and tackle new fields such as design"], "http://www.brown.edu/information-technology/webservices/about/internships-web-services"),
new Entry(["club","hum","cs", "vol"], "September 2016 - Present", 201609, today(), "stanthony", "St. Anthony Hall Co-Ed Literary Fraternity", "Tech Chair (Fall 2016 + Spring 2017), Community Service Chair (Spring 2017), Inclusivity Chair (Spring 2017)", "Providence, RI",
	["Actively participate in the fraternity community-- attend weekly meetings, and during rush season, help with publicity and engage rushees during events.",
	"(Community Service Chair) Send out weekly emails with community service engagements and opportunities at Brown and within Providence."]),
new Entry(["club","hum", "lang"], "Sept 2015 - Present", 201509, today(), "brownaldus", "Aldus Journal of Translation", "Publicity Chair, Copy-Editor, Editor", "Providence, RI",
	["Use Facebook, the website, and email to promote the journal and get new editors as well as submissions", 
	"Meet weekly to review pieces of translation and decide their inclusion in our biyearly journal based on review of both the original work and the translation"], "https://www.facebook.com/aldusjournal/?fref=ts"),
new Entry(["club","hum", "lang"], "Sept 2015 - June 2016", 201509, 201606, "brownjus", "Brown University US-Japan Education and Family Research Lab", "US Team Research Assistant, Japan Team Research Assistant", "Providence, RI",
	["Transcribe and analyze transcripts taken from interviews of Japanese and US mothers on their beliefs about their children and their futures, especially as related to education", 
	"Meet weekly for case analysis meets with each team to discuss individual mothers and how their beliefs may connect to greater systems in the world or specific to either country of interest"], "https://www.facebook.com/USJapanEducationLab"),
new Entry(["club","vol"], "Oct 2015 - Present", 201510, today(), "brownfrn", "Brown University Food Recovery Network", "Brown University Campus Chapter Representative", "Providence, RI",
	["Pick up unsold food from Brown eateries to donate to nearby RI shelters such as the Crossroads Rhode Island homeless shelter and the McAuley House",
	"Contribute to a culture of food waste awareness and help the chapter reach its current poundage (around 7000 - 9000 lbs) of food saved per semester"]),


];
honors = [
new Award(["cs", "women"], "2015", 201502, "ncwit", "National Center for Women & Information Technology", "Award for Aspirations in Computing New York City", "Winner", "", "https://www.aspirations.org/"),
new Award(["natsci"], "Feb 2015", 201502, "danabrain", "The Dana Foundation", "National Design a Brain Experiment Competition", "First Place", "Award for neurobiology grant proposal. <a href='portfolio.html#dana'>See more</a> about this project.", "http://danablog.org/2015/03/16/2015-winners-of-design-a-brain-experiment-competition/"),
new Award(["hum"], "2014", 2014, "mariewanek", "The Mid-Atlantic Association for Asian Studies", "Marie Wanek High School Essay Prize", "First Place", 'Awarded for for essay, “A Sexual WWII: The Key as an Allegory for the Relationship between Japan and the West.” Published online on the Mid-Atlantic Association for Asian Studies page.', "portfolio.html#maaras"),
new Award(["hum"], "Feb 2013", 201302, "scholastic", "Scholastic", "Arts and Writing Awards NYC", "Honorable Mention", "Awarded for Creative Writing piece <a href='portfolio.html#rooted'>'Rooted'</a>", "http://www.artandwriting.org/"),
new Award(["vol"], "2015", 201506, "milken", "Milken Institute, Milken Family Foundation", "Milken Scholar", "", "", "http://www.milkenscholars.org/scholars.taf"),
new Award(["cs", "math"], "2015", 201506, "popisilli", "Design Automation Conference", "P.O. Pistilli Undergraduate Scholarship", "1 of 2 National 2015 Scholars", "", "https://dac.com/content/po-pistilli-undergraduate-scholarship-0"),
new Award(["vol","club"], "2016", 201606, "kimandharold", "Kim and Harold Louie Family Foundation", "Scholar"),
new Award(["hum"], "2015", 201506, "penguinwriting", "Penguin Random House", "Creative Writing Competition", "Artist Recognition Award","", "http://www.penguinrandomhouse.com/creativewriting/"),
new Award(["vol","club"], "2015", 201506,"cumberland", "Cumberland Farms", "Scholar"),
];
school_honors = [
new Award(["cs"], "2015", 201506, "bhseccs", "Bard High School Early College Queens", "Computer Science Award", "Winner"),
new Award(["lang"], "2015", 201506, "bhsecspanish", "Bard High School Early College Queens", "Spanish Language Award", "Winner"),
new Award(["club"], "Sept 2013", 201309,"bhsecstudentlife", "Bard High School Early College Queens", "Student Life Award", "Award presented for involvement in the BHSECQ community at the stepping-up ceremony")
];

courses = [
	new Course("Bard College Associate of Arts", "Spring 2015", 201501, ["cs", "teach"], "Practicum and Theory of Computer Science Education", "Single-Person Independent Study; Introduction to Java Teaching Assistant, etc", "A"),
	new Course("Bard College Associate of Arts", "Spring 2014", 201401, ["cs"], "Object-Oriented Programming", "Introduction to Object Oriented principles in Python", "A"),
	new Course("Bard College Associate of Arts", "Fall 2014", 201409,  ["hum"], "Ancient Japanese Literature", "", "A"),
	new Course("Bard College Associate of Arts", "Fall 2014", 201409, ["cs"], "Introduction to Java, Object-Oriented Programming", "Single-Person Independent Study", "A"),
	new Course("Bard College Associate of Arts", "Spring 2015", 201501,  ["hum"], "Modern Japanese Literature", "", "A"),
	new Course("Bard College Associate of Arts", "Spring 2014", 201409,  ["math"], "Calculus I", "", "A"),
	new Course("Bard College Associate of Arts", "Fall 2014", 201409,  ["math"], "Calculus II", "", "A"),
	new Course("Bard College Associate of Arts", "Fall 2013", 201309,  ["natsci"], "Organic Chemistry I", "", "A"),
	new Course("Bard College Associate of Arts", "Spring 2014", 201401,  ["natsci"], "Organic Chemistry II", "", "A"),
	new Course("Bard College Associate of Arts", "Spring 2014", 201401,  ["natsci"], "Organic Chemistry II", "", "A"),
	new Course("Bard College Associate of Arts", "Fall 2014", 201409,  ["natsci"], "Neurobiology", "", "A"),
	new Course("Bard College Associate of Arts", "Fall 2014", 201409,  ["lang", "hum"], "Cervantes' Don Quixote I", "", "A"),
	new Course("Bard College Associate of Arts", "Spring 2015", 201501,  ["lang", "hum"], "Cervantes' Don Quixote II", "", "A"),
];